### ISSUE TITLE
rotation w.r.t. world should also change translation 

### ISSUE THREAD

**Issue by HiroIshida** [iory/scikit-robot#154]
I have question on the rotation of a coordinate. As the following snippets shows, the worldpos does not change after rotation wrt the world. Because in `initialize` step I set translation to `[1, 0, 0] `, I guess the world pos should be `[0.0, 1.0, 0.0]`. In the corresponding [code](https://github.com/iory/scikit-robot/blob/84d41dfc751b0aa07448c751764340e46ba9b695/skrobot/coordinates/base.py#L798), translation seems not be changed. Is this the correct behaviour? 
```python
import skrobot
import numpy as np
from math import *
from skrobot.coordinates import Coordinates

robot_model = skrobot.models.urdf.RobotModelFromURDF(urdf_file=skrobot.data.pr2_urdfpath())
def initialize():
    robot_model.translation = np.zeros(3)
    robot_model.rotation = np.eye(3)
    robot_model.translate([1.0, 0.0, 0.0])

initialize()
robot_model.rotate(pi*0.5, 'z', 'local')
print(robot_model.worldpos()) #[1.0, 0.0, 0.0] as I expected

initialize()
robot_model.rotate(pi*0.5, 'z', 'world')
print(robot_model.worldpos()) # this is also [1.0, 0.0, 0.0] but I think it's supposed to be [0, 1.0, 0]
```

**Comment by iory** [comment]
It's the correct behavior.
The result of `worldpos` does not change because `robot_model` rotates itself only.

In such a case, you should visualize a result. It helps you.

**Comment by iory** [comment]
https://github.com/iory/scikit-robot/pull/156
The PR adds a notation to this behavior.
