### ISSUE TITLE
Code quality advise

### ISSUE THREAD

**Issue by pigeonsoar** [iory/scikit-robot#163]
Hi, I found a potential problem may be caused in the future (It's worked now.)
In model.py, line 957, function `calc_inverse_kinematics_nspace_from_link_list`, you set a default value (`None`) for paramter `weight`.
Then, it will be passed to function `calc_nspace_from_joint_limit` defined in line 943. And it will cause bug in line 950 if weight is None.

**Comment by iory** [comment]
Thank you for your advise!
How did you find this problem?

**Comment by pigeonsoar** [comment]
> Thank you for your advise!
> How did you find this problem?

I wrote a small tool to check it. 
Thank you for your response.

**Comment by iory** [comment]
> I wrote a small tool to check it.

That's interesting. If it's open source, please let me know!

I'll fix the problem.

**Comment by pigeonsoar** [comment]
> > I wrote a small tool to check it.
> 
> That's interesting. If it's open source, please let me know!
> 
> I'll fix the problem.

I'm Sorry. It is not open source now.  But I will tell you when it is open.

**Comment by pigeonsoar** [comment]
And it has the same problem in line 1356.

**Comment by iory** [comment]
> I'm Sorry. It is not open source now. But I will tell you when it is open.

I'm looking forward using it.
I created PRs to fix this issue.
