### ISSUE TITLE
refactoring around model directory makes examples not working 

### ISSUE THREAD

**Issue by HiroIshida** [iory/scikit-robot#178]
after this https://github.com/iory/scikit-robot/pull/174, 
`example/signed_distance_function.py`
`example/trimesh_scene_viewer.py`
`example/pybullet_robot_interface.py`
are no longer be working, because they all import primitive from `models.primitives`. 

I think maybe running all examples in the github action to check them working is a good practice. But also this makes test slower a lot.

**Comment by iory** [comment]
Thank you for your error reports.
I created a PR to fix the errors.

> I think maybe running all examples in the github action to check them working is a good practice. But also this makes test slower a lot.

It seems good. However, those examples use GUI.
It will take a little bit of time to cope with them.
All users can feel free to report an issue!
