### ISSUE TITLE
viewer fails to visualize mulitple elements  

### ISSUE THREAD

**Issue by HiroIshida** [iory/scikit-robot#202]
## problem description
I want to visualize the following model. 
```xml
<?xml version="1.0" ?>
<robot name="myrobot">
   <link name="base_link">
      <visual>
         <geometry>
            <box size="0.5 0.5 0.1"/>
         </geometry>
         <origin rpy="0.0 -0.0 0.0" xyz="0.0 0.0 0.0"/>
      </visual>
      <visual>
         <geometry>
            <box size="0.5 0.5 0.1"/>
         </geometry>
         <origin rpy="0.0 -0.0 0.0" xyz="0.0 0.0 1.0"/>
      </visual>
   </link>
</robot>
```
where the model is consists of two box with 1m distance.  Let me call above xml file as `test.xml` then I tried to visualize it by the following code: 
```python
import skrobot
robot = skrobot.models.urdf.RobotModelFromURDF(urdf_file="./test.xml")
link = robot.base_link
viewer = skrobot.viewers.TrimeshSceneViewer(resolution=(640, 480))
viewer.add(robot)
viewer.show()
```
However, the result was like the image below, which shows that only single elements is visualized. 
 <img src="https://user-images.githubusercontent.com/38597814/103434914-2ca1ee00-4c4b-11eb-85f0-a1f2ad36dc2b.png" width="300" height="400">

## problem is not in loading multiple urdf mesh
I firstly thought that there is a bug while loading urdf link that has multiple visual elements, but found that there is no such bag by the following trial in interpreter. The result shows that the two visual element is properly loaded and passed to the trimesh scene. Also, we can confirm that two visual elements has 1m distance each other. (see the z component of the vertices).
```bash
In [2]: viewer.scene.geometry
Out[2]: 
OrderedDict([('140623407120144',
              <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>),
             (u'140623407120144:IDQCEYQX9PJF',
              <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>)])
In [4]: viewer.scene.geometry.values()[0].vertices
Out[4]: 
TrackedArray([[-0.25, -0.25, -0.05],
              [-0.25, -0.25,  0.05],
              [-0.25,  0.25, -0.05],
              [-0.25,  0.25,  0.05],
              [ 0.25, -0.25, -0.05],
              [ 0.25, -0.25,  0.05],
              [ 0.25,  0.25, -0.05],
              [ 0.25,  0.25,  0.05]])
In [5]: viewer.scene.geometry.values()[1].vertices
Out[5]: 
TrackedArray([[-0.25, -0.25,  0.95],
              [-0.25, -0.25,  1.05],
              [-0.25,  0.25,  0.95],
              [-0.25,  0.25,  1.05],
              [ 0.25, -0.25,  0.95],
              [ 0.25, -0.25,  1.05],
              [ 0.25,  0.25,  0.95],
              [ 0.25,  0.25,  1.05]])
```

## problem seems not in trimesh side
Next I thought it might be a problem in the trimesh side. So, I tried the following snippets to check it, which directly corresponding the geometries of the above metioned xml file. 
```python
import skrobot
import trimesh
import trimesh.viewer
import numpy as np

robot = skrobot.models.urdf.RobotModelFromURDF(urdf_file="./test.xml")
link = robot.base_link
mesh_list = link.visual_mesh
scene = trimesh.Scene()
scene.add_geometry(mesh_list)
scene.show()
```
The result was the following, which successfully show the two boxes and implies bug is not in the trimesh side. 
<img src="https://user-images.githubusercontent.com/38597814/103435045-c3bb7580-4c4c-11eb-9ead-f6a6a0a36e2f.png" width="300" height="400">

**Comment by iory** [comment]
Is it usual for a `Link` to have two `visual` tags?

**Comment by HiroIshida** [comment]
as long as ROS's documentation, there is no problem doing this. The following reference may help:  
http://wiki.ros.org/urdf/XML/link
https://answers.ros.org/question/101346/how-to-put-multiple-visual-elements-into-a-single-link-in-a-urdf/

**Comment by iory** [comment]
Thanks.
Could you solve this problem?

**Comment by HiroIshida** [comment]
OK! I will try. This is not an urgent problem for me. So maybe take time to solve this though.
