### ISSUE TITLE
AttributeError in loading urdf model if type of transmission tag is written along with transmission instead of as a child tag

### ISSUE THREAD

**Issue by W567** [iory/scikit-robot#293]
If type is written as a child tag of transmission, as in the first figure, there's no error in loading robot model with RobotModelFromURDF.

![unnamed](https://user-images.githubusercontent.com/35333281/233823002-aeebefc5-d5bd-4b62-8666-7d2dfce2cd49.png)

But if type is written along with transmission as shown in the below figure (Default layout from jsk_model_tools?), type can't be found in this case and return None, leading error in loading urdf model.

![unnamed (1)](https://user-images.githubusercontent.com/35333281/233823006-6019c47d-4d38-4944-972e-62206a904deb.png)

Error of loading is shown below.

![unnamed (3)](https://user-images.githubusercontent.com/35333281/233823354-231e6623-d0f6-480f-a5c3-ac5cf44d003a.png)

**Comment by iory** [comment]
Could you upload the URDF that had an error?

**Comment by iory** [comment]
Fixed https://github.com/iory/scikit-robot/pull/300
